### ISSUE TITLE
Version Stable

### ISSUE THREAD

**Issue by mapeveri** [fknop/hapi-learning#26]
I was watching the readme and still the main branch is not stable, it lacks for use in production ?.

There anything I can help?

**Comment by fknop** [comment]
Hi,

The project was mainly a school project, we can't really keep developing it for now because of the lack of time. But a old stable branch should still be available.

But anyway, I don't think it's ready for production out of the box.

**Comment by mapeveri** [comment]
Perfect. Thanks @fknop.
